[versions]
accompanistSystemuicontroller = "0.36.0"
activityCompose = "1.9.3"
agp = "8.8.0"
androidSdk = "11.2.0"
android-minSdk = "24"
android-compileSdk = "34"
appcompat = "1.7.0"
appUpdate = "2.1.0"
browser = "1.8.0"
coreKtx = "1.15.0"
dependencyAnalysis = "2.0.1"
gson = "2.11.0"
hiltAndroid = "2.52"
hiltNavigationCompose = "1.2.0"
kotlinxCoroutinesCore = "1.9.0"
kxml2 = "2.3.0"
libraryBase = "2.1.0"
marineapi = "0.12.0"
material = "1.12.0"
material3 = "1.3.1"
materialIconsExtended = "1.7.5"
navigationCompose = "2.8.4"
playServicesLocation = "21.3.0"
ui = "1.7.5"
volley = "1.2.1"
kotlin = "2.1.0"
realm = "2.1.0"
ksp = "2.1.0-1.0.29"
serialization = "1.8.0"
appauth = "0.11.1"
lifecycleRuntimeKtx = "2.8.7"
composeBom = "2024.11.00"
ktor = "3.0.3"
logback = "1.5.16"
koin = "4.0.1"
koin-annotations = "1.4.0"
dc-polyfill = "1.0.0-SNAPSHOT"
dc-aviator = "1.0.0-SNAPSHOT"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
material = { module = "com.google.android.material:material", version.ref = "material" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources-jvm" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression-jvm" }
ktor-server-forwarded-header = { module = "io.ktor:ktor-server-forwarded-header-jvm" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm" }
ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml-jvm" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-annotations-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
dc-polyfill = { module = "cloud.mallne.dicentra:polyfill", version.ref = "dc-polyfill" }
dc-aviator-core = { module = "cloud.mallne.dicentra.aviator:core", version.ref = "dc-aviator" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kjvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }